// Code generated by "goki version"; DO NOT EDIT.

package main

const (
	// Version is the version of this package being used
	Version = "v0.0.23"
	// GitCommit is the commit just before the latest version commit
	GitCommit = "812d7bf"
	// VersionDate is the date-time of the latest version commit in UTC (in the format 'YYYY-MM-DD HH:MM', which is the Go format '2006-01-02 15:04')
	VersionDate = "2023-12-12 20:48"
)
